### ISSUE TITLE
Missing field names in errors thrown by class validator

### ISSUE THREAD

**Issue by lewispham** [mercurius-js/mercurius#458]
As I'm trying to integrate typegraphql with mercurius, validation errors thrown by class validator are always this error.
```
Error: Argument Validation Error
    at Object.validateArg (/app/node_modules/type-graphql/dist/resolvers/validate-arg.js:29:15)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Promise.all (index 0)
    at Object.fastifyGraphQl [as graphql] (/app/node_modules/mercurius/index.js:516:23) {
  locations: [ { line: 2, column: 3 } ],
  path: [ 'createUser' ]
}
```
As you can see from the error log then the related field names are not included. Shouldn't they be included in the field `extensions` (ErrorWithProps) automatically?

P/s. Related issue on typegraphql repo https://github.com/MichalLytek/type-graphql/issues/863

**Comment by mcollina** [comment]
I think we are missing a property called `originalError` in our error handler.


Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by lewispham** [comment]
@mcollina I think I'm not yet qualified for having that PR. Please help with it. Thanks.

**Comment by simone-sanfratello** [comment]
Worked on that, I haven't found a solution.

I see `type-graphql` create the whole schema with resolvers, then schema is executed at https://github.com/mercurius-js/mercurius/blob/master/index.js#L527

but then error contained in `context` is already a `GraphQLError` and details are missing.

I haven't found some options to pass to the `graphql.execute` function to get the `originalError`

**Comment by angelvega93** [comment]
I'm having this problem right now, still no solution?

**Comment by gilach** [comment]
Picking the issue up - will update with the progress.

**Comment by gilach** [comment]
I've managed to reproduce the scenario mentioned above. The `originalError` is actually contained within the errors in `ExecutionResult` object. 

The default error formatter is not rendering details about the validation results, because of how `type-graphql` creates the error object (ie. `apollo-server` uses `extensions` field to send additional information whereas `type-graphql` does not). To access the `originalError` you could for example use `errorFormatter` option (see [here](https://mercurius.dev/#/docs/api/options?id=plugin-options)) which will provide previously mentioned `ExecutionResult` object that contains the errors in their original form (how `type-graphql` provides them).

**Comment by mcollina** [comment]
@gilach can you add a quick solution here that would help solve this? Also, could we include some info on that in our docs? It seems error formatting is one of our weak spots.

**Comment by gilach** [comment]
Sure. Here's a simple example of how you could define your own error formatter:
```
    const app = fastify();
    const opts: FastifyRegisterOptions<MercuriusOptions> = {
        schema,
        graphiql: true,
        errorFormatter: (executionResult, context) => {
            const log = context.reply ? context.reply.log : context.app.log;
            log.info({ err: executionResult.errors }, 'Argument Validation Error');
            return {
                statusCode: 201,
                response: {
                    data: executionResult.data,
                    errors: executionResult.errors
                }
            }
        }
    }
    app.register(mercurius, opts);
```

Now, in this case, it gets a little more complicated. The problem is that validation errors coming from `type-graphql` are stored in `originalError` field which is non-enumerable (meaning it won't get serialized/logged - this is a design decision made by `graphql-js` in their implementation of GraphQLError class). An easy workaround would be to either make it enumerable or copy it over to `extensions` field. As for the second option, the problem is that in GraphQLError's constructor method if the extensions are empty initially then it makes this field non-enumerable as well. To hack around it you could do something like this:
```
    const opts: FastifyRegisterOptions<MercuriusOptions> = {
        schema,
        graphiql: true,
        errorFormatter: (executionResult, context) => {
            const log = context.reply ? context.reply.log : context.app.log;
            const errors = executionResult.errors.map((error) => {
                error.extensions.exception = error.originalError;
                Object.defineProperty(error, 'extensions', {enumerable: true});
                return error;
            });
            log.info({ err: executionResult.errors }, 'Argument Validation Error');
            return {
                statusCode: 201,
                response: {
                    data: executionResult.data,
                    errors
                }
            }
        }
    }
```

Hopefully, that gives an idea of what could be done here on that matter.

**Comment by gilach** [comment]
We have a separate doc about integration with `type-graphql`, so I will definitely mention this there.
