### ISSUE TITLE
Relay Support

### ISSUE THREAD

**Issue by EstebanBorai** [mercurius-js/mercurius#828]
Hi, I'm checking out this library and I'm curious about using it along with
Relay support. I also found [GraphQL-Relay][1] repo from the GraphQL
organization and Im wondering if it could be used along with Mercurius.

My goal is to achieve a GraphQL schema using connections as explained
in [this article from Apollo GraphQL Blog][2].

Thanks in advance!

[1]: https://github.com/graphql/graphql-relay-js
[2]: https://www.apollographql.com/blog/graphql/explaining-graphql-connections/

**Comment by smolinari** [comment]
This should have been a question in the Discussions. 

At any rate, how you build out the server itself is up to you. Mercurius is much lower level and allows basically for anything you want in terms of schema design and automation, which Relay is basically about. For instance, I'm using Mercurius with NestJS and a library called nestjs-query. It handles a lot of automation for generating the schema based simply on entities and DTOs, which are the only things I need to "design", somewhat similar to what Relay can offer. There is some additional boilerplate needed, due to the module system of NestJS. But, that is the cost of the automation and also for allowing for larger system design too. If you are working on a smaller project, what I am using would be overkill. 

But, to answer your question directly, yes, you can build out a Relay compliant server with Mercurius. Though, I'm not certain you can just throw in that Graphql-Relay library you pointed to and it will work and also note that package is somewhat outdated/ seems abandoned. You will also would need to use the [Relay client](https://relay.dev/) and that will basically tie your hands to React. Maybe that is also something you want or maybe not, so just sayin... :shrug: 

Scott

**Comment by EstebanBorai** [comment]
Thanks so much @smolinari!
